services:
    jgp_menu.menu.renderer:
        class: Jagilpe\MenuBundle\Renderer\MenuRenderer
        calls:
            - [ setContainer, [ "@service_container" ] ]
        
    jgp_menu.menu_builder.factory:
        class: Jagilpe\MenuBundle\Factory\MenuBuilderFactory
        arguments:
          - "@request_stack"
          - "@router"   
               
    # Twig Extension
    jgp_menu.twig_extension:
        class: Jagilpe\MenuBundle\Twig\JagilpeMenuExtension
        arguments:
            - "@jgp_menu.menu.renderer"
        public: false
        tags:
            - { name: twig.extension }