services:
    m7_menu.menu.renderer:
        class: Module7\MenuBundle\Renderer\MenuRenderer
        arguments: [ "@templating" ]
        
    m7_menu.menu_builder.factory:
        class: Module7\MenuBundle\Factory\MenuBuilderFactory
        arguments:
          - "@request_stack"
          - "@router"   
               
    # Twig Extension
    m7_menu.twig_extension:
        class: Module7\MenuBundle\Twig\Module7MenuExtension
        public: false
        tags:
            - { name: twig.extension }